Repository openshift-pipelines/tektoncd-catalog, pull requests merged in 2023-08, with the labels that each got.

#33 Add support for folders on `catalogcd-cmd lint`
  internal/cmd/lint.go
Labels: approved, lgtm

#35 Add a small `design.md` document.
  docs/design.md
Labels: approved, lgtm

#36 Reusable GitHub Actions
  .github/actions/go/action.yaml
  .github/actions/tektoncd/action.yaml
  .github/workflows/generate-catalogs.yaml
  .github/workflows/images.yaml
  .github/workflows/test-kubernetes-tasks.yaml
Labels: github_actions, approved, lgtm

#37 TKNECO-69: Best Practices (Linter Policies)
  docs/lint.md
Labels: approved, lgtm, jira/valid-reference

#39 TKNECO-87: `.catalog.yaml`
  docs/dot-catalog.md
Labels: documentation, approved, lgtm, jira/valid-reference
